BEGIN EXECUTE IMMEDIATE 'DROP TABLE Economic_Observation CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Weather_Observation CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Sales_Fact CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Date_Dim CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Store CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE Store (
    StoreID NUMBER PRIMARY KEY
);

CREATE TABLE Date_Dim (
    DateID DATE PRIMARY KEY,
    WeekStartDate DATE NOT NULL,
    WeekOfYear NUMBER NOT NULL,
    MonthNum NUMBER NOT NULL,
    QuarterNum NUMBER NOT NULL,
    YearNum NUMBER NOT NULL,
    IsHolidayWeek NUMBER(1) NOT NULL CHECK (IsHolidayWeek IN (0,1))
);

CREATE TABLE Sales_Fact (
    StoreID NUMBER NOT NULL,
    DateID DATE NOT NULL,
    Weekly_Sales NUMBER(12,2) NOT NULL,
    Holiday_Flag NUMBER(1) NOT NULL CHECK (Holiday_Flag IN (0,1)),
    CONSTRAINT pk_sales_fact PRIMARY KEY (StoreID, DateID),
    CONSTRAINT fk_sales_store FOREIGN KEY (StoreID) REFERENCES Store(StoreID),
    CONSTRAINT fk_sales_date FOREIGN KEY (DateID) REFERENCES Date_Dim(DateID)
);

CREATE TABLE Weather_Observation (
    StoreID NUMBER NOT NULL,
    DateID DATE NOT NULL,
    Temperature NUMBER(6,2),
    CONSTRAINT pk_weather PRIMARY KEY (StoreID, DateID),
    CONSTRAINT fk_weather_store FOREIGN KEY (StoreID) REFERENCES Store(StoreID),
    CONSTRAINT fk_weather_date FOREIGN KEY (DateID) REFERENCES Date_Dim(DateID)
);

CREATE TABLE Economic_Observation (
    StoreID NUMBER NOT NULL,
    DateID DATE NOT NULL,
    Fuel_Price NUMBER(6,3),
    CPI NUMBER(10,3),
    Unemployment NUMBER(6,3),
    CONSTRAINT pk_economic PRIMARY KEY (StoreID, DateID),
    CONSTRAINT fk_economic_store FOREIGN KEY (StoreID) REFERENCES Store(StoreID),
    CONSTRAINT fk_economic_date FOREIGN KEY (DateID) REFERENCES Date_Dim(DateID)
);